BASE_CONHECIMENTO = {
    "micose_superficial": {
        "sintomas": { "prurido": 1 },
        "sinais":   { "descamacao": 1, "placas_eritematosas": 1, "bordas_circinadas": 1, "escamas": 1 },
        "local":    { "palmo_plantar": 1, "couro": 1, "unha": 1, "tronco": 1, "dobras": 1},
        "idade":    { "bebe": 0, "crianca": 0, "adulto_jovem": 0, "adulto": 0, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 0 },
        "historico":{ "diabetes": 1, "ambiente_umido": 1, "sapatos_fechados": 1, "fatores_geneticos": 1, "atopia": 1 },
        "alergia":  { "nao": 0, "nao_sei": 0 }
    },

    "sifilis": {
        "sintomas": { "assintomatico": 1 },
        "sinais":   { "eritema": 1, "ulcera": 1 },
        "local":    { "disseminado": 1, "palmo_plantar": 1 },
        "idade":    { "bebe": 0, "crianca": 0, "adulto_jovem": 1, "adulto": 0, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 0 },
        "historico":{ "contato_sexual_desprotegido": 3 },
        "alergia":  { "nao": 0, "nao_sei": 0 }
    },

    "hanseniase": {
        "sintomas": { "formigamento": 1, "sensibilidade": 1, "dormencia": 1 },
        "sinais":   { "macula": 2 },
        "local":    { "disseminado": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adulto_jovem": 0, "adulto": 0, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 0 },
        "historico":{ "contato_casos_familiares": 3 },
        "alergia":  { "nao": 0, "nao_sei": 0 }
    },

    "herpes_simples": {
        "sintomas": { "prurido": 1, "ardor": 1, "dor": 1, "formigamento": 1, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 1, "edema": 0, "vesicula": 2, "bolhas": 0, "fissura": 0, "ressecamento": 0, "descamacao": 0,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 0, "palmo_plantar": 0, "couro": 0, "unha": 0, "tronco": 0, "dobras": 0, "labios": 2, "genitais": 2,
                     "face": 0, "flexoras": 0, "membros": 0, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 0, "adulto_jovem": 2, "adulto": 0, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 0 },
        "historico":{ "diabetes": 0, "imunossupressao": 1, "estresse": 1, "asma": 0, "rinite": 0, "dermatite": 0, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 0,
                     "contato_casos_familiares": 0, "exposicao_solar": 2, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 0, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },
    
    "dermatite_atopica": {
        "sintomas": { "prurido": 1, "ardor": 0, "dor": 0, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 1, "edema": 0, "vesicula": 0, "bolhas": 0, "fissura": 0, "ressecamento": 1, "descamacao": 1,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 0, "palmo_plantar": 0, "couro": 0, "unha": 0, "tronco": 0, "dobras": 0, "labios": 2, "genitais": 2,
                     "face": 1, "flexoras": 1, "membros": 1, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 2, "crianca": 2, "adolescente": 0, "adulto_jovem": 1, "adulto": 1, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 0 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 0, "asma": 1, "rinite": 1, "dermatite": 1, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 1, "contato_sexual_desprotegido": 0, "atopia": 1,
                     "contato_casos_familiares": 0, "exposicao_solar": 0, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 0, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },

    "dermatite_contato": {
        "sintomas": { "prurido": 1, "ardor": 1, "dor": 0, "formigamento": 1, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 1, "edema": 1, "vesicula": 1, "bolhas": 1, "fissura": 0, "ressecamento": 0, "descamacao": 0,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 0, "palmo_plantar": 0, "couro": 0, "unha": 0, "tronco": 0, "dobras": 0, "labios": 2, "genitais": 2,
                     "face": 0, "flexoras": 0, "membros": 0, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 0, "adulto_jovem": 1, "adulto": 1, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 0 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 0, "asma": 0, "rinite": 0, "dermatite": 1, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 0,
                     "contato_casos_familiares": 0, "exposicao_solar": 0, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 3, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 0, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },

    "dermatite_estase": {
        "sintomas": { "prurido": 0, "ardor": 0, "dor": 1, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 0, "edema": 1, "vesicula": 0, "bolhas": 0, "fissura": 0, "ressecamento": 0, "descamacao": 0,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 0, "palmo_plantar": 0, "couro": 0, "unha": 0, "tronco": 0, "dobras": 0, "labios": 0, "genitais": 0,
                     "face": 0, "flexoras": 0, "membros": 2, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 0, "adulto_jovem": 0, "adulto": 1, "idoso": 2 },
        "sexo":     { "masculino": 0, "feminino": 1 },
        "historico":{ "diabetes": 0, "imunossupressao": 1, "estresse": 1, "asma": 0, "rinite": 0, "dermatite": 0, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 0,
                     "contato_casos_familiares": 0, "exposicao_solar": 2, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 3, "obesidade": 2, "artrites_deformantes": 2, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 0, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },

    "eczema_disidrotico": {
        "sintomas": { "prurido": 1, "ardor": 0, "dor": 0, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 0, "edema": 0, "vesicula": 1, "bolhas": 1, "fissura": 1, "ressecamento": 1, "descamacao": 1,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 0, "palmo_plantar": 1, "couro": 0, "unha": 0, "tronco": 0, "dobras": 0, "labios": 0, "genitais": 0,
                     "face": 0, "flexoras": 0, "membros": 0, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 0, "adulto_jovem": 2, "adulto": 0, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 1 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 1, "asma": 0, "rinite": 0, "dermatite": 0, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 1,
                     "contato_casos_familiares": 0, "exposicao_solar": 2, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 2,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 0, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },

    "liquen_simples_cronico": {
        "sintomas": { "prurido": 2, "ardor": 0, "dor": 0, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 0, "edema": 0, "vesicula": 0, "bolhas": 0, "fissura": 0, "ressecamento": 0, "descamacao": 0,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 2, "sulcos": 2, "hiperpigmentacao": 2, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 0, "palmo_plantar": 0, "couro": 0, "unha": 0, "tronco": 0, "dobras": 0, "labios": 0, "genitais": 1,
                     "face": 0, "flexoras": 0, "membros": 1, "nuca": 1, "sacra": 2 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 0, "adulto_jovem": 1, "adulto": 1, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 0 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 1, "asma": 0, "rinite": 0, "dermatite": 1, "ansiedade": 1,
                     "doencas_autoimunes": 0, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 1,
                     "contato_casos_familiares": 0, "exposicao_solar": 0, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 2, "oleosidade": 0, "infeccao_viral_previa": 0, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },

    "dermatite_seborreica": {
        "sintomas": { "prurido": 1, "ardor": 0, "dor": 0, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 1, "edema": 0, "vesicula": 0, "bolhas": 0, "fissura": 0, "ressecamento": 0, "descamacao": 1,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 0, "palmo_plantar": 0, "couro": 1, "unha": 0, "tronco": 0, "dobras": 0, "labios": 2, "genitais": 2,
                     "face": 1, "flexoras": 0, "membros": 0, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 1, "adulto_jovem": 1, "adulto": 1, "idoso": 0 },
        "sexo":     { "masculino": 1, "feminino": 0 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 1, "asma": 0, "rinite": 0, "dermatite": 0, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 0,
                     "contato_casos_familiares": 0, "exposicao_solar": 0, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 2, "infeccao_viral_previa": 0, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },

    "psoriase": {
        "sintomas": { "prurido": 1, "ardor": 0, "dor": 0, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 0, "edema": 0, "vesicula": 0, "bolhas": 0, "fissura": 0, "ressecamento": 0, "descamacao": 0,
                     "placas_eritematosas": 1, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 2, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 0, "palmo_plantar": 0, "couro": 1, "unha": 0, "tronco": 0, "dobras": 0, "labios": 0, "genitais": 0,
                     "face": 0, "flexoras": 1, "membros": 0, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 0, "adulto_jovem": 2, "adulto": 0, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 0 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 1, "asma": 0, "rinite": 0, "dermatite": 0, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 2, "contato_sexual_desprotegido": 0, "atopia": 0,
                     "contato_casos_familiares": 0, "exposicao_solar": 0, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 0, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },

    "pitiriase_rosea": {
        "sintomas": { "prurido": 1, "ardor": 0, "dor": 0, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 1},
        "sinais":   { "eritema": 0, "edema": 0, "vesicula": 0, "bolhas": 0, "fissura": 0, "ressecamento": 0, "descamacao": 0,
                     "placas_eritematosas": 1, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 1,
                     "erupcoes_tronco": 1, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 0, "palmo_plantar": 0, "couro": 0, "unha": 0, "tronco": 1, "dobras": 0, "labios": 0, "genitais": 0,
                     "face": 0, "flexoras": 0, "membros": 0, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 1, "adulto_jovem": 1, "adulto": 0, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 0 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 0, "asma": 0, "rinite": 0, "dermatite": 0, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 0,
                     "contato_casos_familiares": 0, "exposicao_solar": 0, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 2, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },
    
    "eritrodermia_esfoliativa": {
        "sintomas": { "prurido": 1, "ardor": 0, "dor": 0, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 0, "edema": 0, "vesicula": 0, "bolhas": 0, "fissura": 0, "ressecamento": 0, "descamacao": 0,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 2, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 2, "palmo_plantar": 0, "couro": 0, "unha": 0, "tronco": 0, "dobras": 0, "labios": 0, "genitais": 0,
                     "face": 0, "flexoras": 0, "membros": 0, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 0, "adulto_jovem": 0, "adulto": 1, "idoso": 1 },
        "sexo":     { "masculino": 0, "feminino": 0 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 0, "asma": 0, "rinite": 0, "dermatite": 0, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 0,
                     "contato_casos_familiares": 0, "exposicao_solar": 0, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 0, "psoriase": 2, "reacao_medicamentosa": 1,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 1, "sulfas": 1, "antibioticos": 1, "nao": 0, "nao_sei": 0 }
    },

    "parapsoriase": {
        "sintomas": { "prurido": 1, "ardor": 0, "dor": 0, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 1, "edema": 0, "vesicula": 0, "bolhas": 0, "fissura": 0, "ressecamento": 0, "descamacao": 0,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 0},
        "local":    { "disseminado": 0, "palmo_plantar": 0, "couro": 0, "unha": 0, "tronco": 1, "dobras": 0, "labios": 0, "genitais": 0,
                     "face": 0, "flexoras": 0, "membros": 1, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 0, "adulto_jovem": 0, "adulto": 1, "idoso": 0 },
        "sexo":     { "masculino": 1, "feminino": 0 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 0, "asma": 0, "rinite": 0, "dermatite": 0, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 0,
                     "contato_casos_familiares": 0, "exposicao_solar": 0, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 0, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 2},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },

    "eritema_multiforme": {
        "sintomas": { "prurido": 1, "ardor": 0, "dor": 0, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 0, "edema": 0, "vesicula": 1, "bolhas": 1, "fissura": 0, "ressecamento": 0, "descamacao": 0,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 2, "nodulo": 0},
        "local":    { "disseminado": 1, "palmo_plantar": 0, "couro": 0, "unha": 0, "tronco": 0, "dobras": 0, "labios": 0, "genitais": 0,
                     "face": 0, "flexoras": 0, "membros": 0, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 0, "adulto_jovem": 1, "adulto": 0, "idoso": 0 },
        "sexo":     { "masculino": 1, "feminino": 0 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 0, "asma": 0, "rinite": 0, "dermatite": 0, "ansiedade": 0,
                     "doencas_autoimunes": 0, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 0,
                     "contato_casos_familiares": 0, "exposicao_solar": 0, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 1, "psoriase": 0, "reacao_medicamentosa": 1,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 1, "sulfas": 1, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    },

    "eritema_nodoso": {
        "sintomas": { "prurido": 0, "ardor": 1, "dor": 1, "formigamento": 0, "sensibilidade": 0, "dormencia": 0 , "assintomatico": 0},
        "sinais":   { "eritema": 0, "edema": 0, "vesicula": 0, "bolhas": 0, "fissura": 0, "ressecamento": 0, "descamacao": 0,
                     "placas_eritematosas": 0, "bordas_circinadas": 0, "escamas": 0, "ulcera": 0, "macula": 0, "dermatite": 0,
                     "placa_liquenificada": 0, "sulcos": 0, "hiperpigmentacao": 0, "bordas_definidas": 0, "placa_mae": 0,
                     "erupcoes_tronco": 0, "erupcao_eritemato_descamativa": 0, "lesoes_alvo": 0, "nodulo": 2},
        "local":    { "disseminado": 0, "palmo_plantar": 0, "couro": 0, "unha": 0, "tronco": 0, "dobras": 0, "labios": 0, "genitais": 0,
                     "face": 0, "flexoras": 0, "membros": 1, "nuca": 0, "sacra": 0 },
        "idade":    { "bebe": 0, "crianca": 0, "adolescente": 0, "adulto_jovem": 1, "adulto": 0, "idoso": 0 },
        "sexo":     { "masculino": 0, "feminino": 1 },
        "historico":{ "diabetes": 0, "imunossupressao": 0, "estresse": 0, "asma": 0, "rinite": 0, "dermatite": 0, "ansiedade": 0,
                     "doencas_autoimunes": 2, "fatores_geneticos": 0, "contato_sexual_desprotegido": 0, "atopia": 0,
                     "contato_casos_familiares": 0, "exposicao_solar": 0, "ambiente_umido": 0, "sapatos_fechados": 0,
                     "contato_agentes_irritantes": 0, "varizes": 0, "obesidade": 0, "artrites_deformantes": 0, "eczema": 0,
                     "picadas_inseto": 0, "oleosidade": 0, "infeccao_viral_previa": 1, "psoriase": 0, "reacao_medicamentosa": 0,
                     "nenhum_especifico": 0},
        "alergia":  { "anticonvulsivantes": 0, "sulfas": 0, "antibioticos": 0, "nao": 0, "nao_sei": 0 }
    }
}